matmul/tests/CMakeLists.txt
matmul/tests/generate_e2e_matmul_tests.py

The comment on `infer_acc_type` was outdated and making the argument required will simplify the generator.

Make matmul generator acc_type argument required/explicit.

---

onnx_ops/conftest.py

Fixes https://github.com/nod-ai/SHARK-TestSuite/issues/319
* Sample compile error logs: https://gist.github.com/ScottTodd/1fbb40a72b226464b9ec2a1396880914
* Sample run error logs: https://gist.github.com/ScottTodd/111320271f012f42f984fdd5cfc65186

Log input files and test case paths when ONNX tests fail.

---

linalg_ops/matmul/CMakeLists.txt

This fixes the build error reported here: https://github.com/iree-org/iree-test-suites/pull/22#issuecomment-2414925619

Only enable hip tests if IREE_HIP_TEST_TARGET_CHIP is set.

---

linalg_ops/iree_test_suites_runner_test.cmake
linalg_ops/matmul/CMakeLists.txt

The `COMPILER_ARGS` option was getting ignored since `COMPILER_FLAGS` is what the helper function was checking.
Probably some copy/paste bug when forking from https://github.com/iree-org/iree/blob/main/build_tools/cmake/iree_e2e_generated_runner_test.cmake where `COMPILER_FLAGS` and `RUNNER_ARGS` are used. I think it makes sense to just call both `ARGS` or `FLAGS`.

Fix mismatch between CMake option names.

---

linalg_ops/CMakeLists.txt
linalg_ops/attention/CMakeLists.txt
linalg_ops/attention/generate_e2e_attention_tests.py
linalg_ops/attention/generate_test_mlir_files.sh
linalg_ops/attention/generated/f16_f16_f16_f16/attention_f16_f16_f16_f16_large.mlir
linalg_ops/attention/generated/f16_f16_f16_f16/attention_f16_f16_f16_f16_large_calls.mlir
linalg_ops/attention/generated/f16_f16_f16_f16/attention_f16_f16_f16_f16_medium.mlir
linalg_ops/attention/generated/f16_f16_f16_f16/attention_f16_f16_f16_f16_medium_calls.mlir
linalg_ops/attention/generated/f16_f16_f16_f16/attention_f16_f16_f16_f16_small.mlir
linalg_ops/attention/generated/f16_f16_f16_f16/attention_f16_f16_f16_f16_small_calls.mlir
linalg_ops/iree-e2e-attention-test.cc

Progress on this https://github.com/iree-org/iree-test-suites/issues/2
This PR refactors, adds, and migrates Attention e2e tests from the PR here: https://github.com/iree-org/iree/pull/18320

Add Attention Test Suite

---

linalg_ops/requirements-iree.txt
onnx_models/requirements-iree.txt
onnx_ops/requirements-dev.txt
onnx_ops/requirements-iree.txt

Package names and the install method changed with https://github.com/iree-org/iree/releases/tag/iree-3.0.0.

Update workflows to use latest IREE nightly packages.

---

onnx_models/conftest.py

This should improve test time without affecting performance. When running on the same machine that is used to compile, this flag is recommended.

Use host for llvmcpu compilation in onnx model tests.

---

onnx_models/conftest.py
onnx_models/utils.py

Similar to https://github.com/iree-org/iree-test-suites/pull/42, this updates the onnx_models tests to use the new built-in version upgrade code included in `iree-import-onnx`.

Switch ONNX model tests to use `--opset-version` built in conversion.

---

onnx_models/README.md
onnx_models/tests/model_zoo/README.md
onnx_models/tests/model_zoo/validated/vision/README.md
onnx_models/tests/model_zoo/validated/vision/classification_models_test.py

Description | Path example
-- | --
Before | `onnx_models/tests/vision/classification_models_test.py`
After | `onnx_models/tests/model_zoo/validated/vision/classification_models_test.py`
This now mirrors the structure in the upstream onnx/models repository more closely: https://github.com/onnx/models/tree/main/validated/vision, in preparation for adding tests for the non-validated models or models from other sources like https://huggingface.co/models.

Move ONNX vision model tests under model_zoo/validated.

---

.github/workflows/test_onnx_models.yml
onnx_models/README.md
onnx_models/pytest.ini
onnx_models/tests/model_zoo/validated/vision/body_analysis_models_test.py
onnx_models/tests/model_zoo/validated/vision/classification_models_test.py
onnx_models/tests/model_zoo/validated/vision/object_detection_segmentation_models_test.py
onnx_models/tests/model_zoo/validated/vision/style_transfer_models_test.py
onnx_models/tests/model_zoo/validated/vision/super_resolution_models_test.py

This test suite now contains all model categories from https://github.com/onnx/models/tree/main/validated/vision.
Description | Logs | Summary
-- | -- | --
Before | https://github.com/iree-org/iree-test-suites/actions/runs/11965059466/job/33358435820 | `12 passed, 5 xfailed in 160.89s`
After | https://github.com/iree-org/iree-test-suites/actions/runs/11965072359/job/33358474549?pr=46 | `21 passed, 3 skipped, 13 xfailed in 444.04s`
Note that downstream can choose to run with `pytest -m "not size_large"` to exclude the especially large tests.
I did not add test cases for duplicates, even though some may be useful to test. For example the https://github.com/onnx/models/tree/main/validated/vision/object_detection_segmentation/duc/model folder has these files:
* `ResNet101-DUC-12-int8.onnx`
* …

Import tests for all remaining validated/vision/ folders.

---

onnx_models/tests/model_zoo/validated/vision/classification_models_test.py

Flagged by this nightly CI run: https://github.com/iree-org/iree-test-suites/actions/runs/12201314112.
Fixed by https://github.com/iree-org/iree/pull/19356. I linked some logs at https://github.com/iree-org/iree/pull/19356#issuecomment-2523547585.

Mark onnx model test_mobilenet as passing.

---

sharktank_models/llama3.1/test_llama.py

Changed multi device configuration to support separate device compilation instead of multiples of the same device. Add compile flag to avoid numerical error known on `hip`.

Rework hip and multi device configuration

---

.github/workflows/test_linalg_ops.yml
.github/workflows/test_onnx_models.yml
.github/workflows/test_onnx_ops.yml
.github/workflows/test_sharktank_models.yml

These jobs are still runnable in forks via `pull_request` and `workflow_dispatch` triggers, but this still skip the `schedule` triggers in forks that do not have the workflows or scheduled jobs disabled.
Most jobs are currently fast and use free resources, but the new sharktank model tests do use git LFS quota, so we want to limit wasteful usage there to avoid issues like https://github.com/iree-org/iree-test-suites/issues/56.

Limit scheduled jobs to only run in iree-org.

---

sharktank_models/llama3.1/assets/toy_llama.mlir
sharktank_models/llama3.1/assets/toy_llama_tp2.mlir
sharktank_models/llama3.1/test_llama.py

Previous version was based on decopmosed attention for prefill and
decode. This migrates to flash attention instead and changes blocking
size to 32.
Signed-off-by: Rob Suderman <rob.suderman@gmail.com>

Migrate to flash attention for attention operation

---

onnx_models/README.md
sharktank_models/README.md

It turns `l` from lowercase to uppercase.

[NFC] Fix a typo in README.md (HTMl -> HTML)

---

.github/workflows/test_linalg_ops.yml
.github/workflows/test_litert_models.yml
.github/workflows/test_onnx_models.yml
.github/workflows/test_onnx_ops.yml
.github/workflows/test_sharktank_models.yml

Actions are pinned with hashes as suggested by OpenSSF Scorecard, see https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.

Pin github action versions to commit hashes.

---

.github/dependabot.yml

Actions are pinned with hashes as suggested by OpenSSF Scorecard, see https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies. Those actions get now upgraded by using Depandabot, see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot.

Update GH actions with Dependabot.

---

litert_models/tests/kaggle/tensorflow/mobilenet_v1_test.py

Newly failing (as expected) after https://github.com/iree-org/iree/pull/19683.

Mark tflite mobilenet test as xfail, pending TOSA v1.0 changes.

---

onnx_ops/README.md

At some point the `\n` stopped being respected:

Fix mermaidjs markdown rendering for onnx ops diagrams.

---

.github/workflows/test_onnx_models.yml
onnx_models/README.md
onnx_models/cache.py
onnx_models/conftest.py
onnx_models/tests/model_zoo/validated/vision/body_analysis_models_test.py
onnx_models/tests/model_zoo/validated/vision/classification_models_test.py
onnx_models/tests/model_zoo/validated/vision/object_detection_segmentation_models_test.py
onnx_models/tests/model_zoo/validated/vision/style_transfer_models_test.py
onnx_models/tests/model_zoo/validated/vision/super_resolution_models_test.py
onnx_models/utils.py

Progress on https://github.com/iree-org/iree-test-suites/issues/6.
This adds a caching layer which allows developers and persistent CI runners to avoid needing to redownload source `.onnx` files.
* The cache location defaults to `${IREE_TEST_FILES}/iree-test-suites` if `IREE_TEST_FILES` is set, or `~/.cache/iree-test-suites/` otherwise. This can be overridden with the custom `--cache-dir=/path/to/cache` pytest option. Several of our persistent CI machines set the `IREE_TEST_FILES` environment variable already.
* The cache is implemented as a local git clone of the https://github.com/onnx/models repository, which uses [Git Large File Storage (LFS)](https://git-lfs.com/) to store large files. When a file is requested by a test, the cache layer runs `git lfs pull` in the local clone to fetch …

Implement caching for onnx/models git LFS files.

---

litert_models/requirements.txt
litert_models/tests/kaggle/tensorflow/mobilenet_v1_test.py

Since tensorflow has released a new version, the tests are currently failing due to an import error. Updating the tests to reflect expected import error and xfail on those tests

Fixing Litert Models test to reflect import error

---

sharktank_models/action.yml

Ah! Messed up the GH path, [docs about `GITHUB_ACTION_PATH`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables)
resolves issue in iree build

Fixing GH action path

---

sharktank_models/benchmarks/model_benchmark_run.py

Add _initrequest for pytest-retry to avoid AttributeError for sharktank tests. Sometimes the CI fails with an AttributeError:
```
INTERNALERROR> AttributeError: 'ModelBenchmarkRunItem' object has no attribute '_initrequest'
---------------------------- live log sessionfinish ----------------------------
INFO     conftest:conftest.py:99 Pytest benchmark test session has finished
```

Add _initrequest for pytest-retry to avoid AttributeError for sharktank tests

---

sharktank_models/README.md
sharktank_models/quality_tests/README.md

- Remove `cd sharktank_models` from the setup because other commands assume users being at the root directory.
- Add missing periods at the end.
- Remove unnecessary whitespace from `git lfs`.
- Make style more consistent.

[NFC] Update example commands and fix typos.
